inherit_from: .rubocop_todo.yml

AllCops:
  TargetRubyVersion: 3.3
  NewCops: enable
  Exclude:
    - 'vendor/**/*'
    - '_ignore/**/*'

Gemspec/DevelopmentDependencies:
  EnforcedStyle: gemspec

Gemspec/RequireMFA:
  Enabled: false

Gemspec/RequiredRubyVersion:
  Enabled: false
