inherit_from: .rubocop_todo.yml

AllCops:
  TargetRubyVersion: 2.7
  NewCops: enable
  Exclude:
    - 'vendor/**/*'
    - '_ignore/**/*'

Gemspec/RequireMFA:
  Enabled: false

Gemspec/RequiredRubyVersion:
  Enabled: false
